// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/moves-variant/ContextFirst.tsx": () => import("../components/mockups/moves-variant/ContextFirst.tsx"),
  "./components/mockups/moves-variant/MoodBoard.tsx": () => import("../components/mockups/moves-variant/MoodBoard.tsx"),
  "./components/mockups/moves-variant/WarmEditorial.tsx": () => import("../components/mockups/moves-variant/WarmEditorial.tsx"),
  "./components/mockups/templates/EditorialGreenBankingDashboard-PKLFy6/App.tsx": () => import("../components/mockups/templates/EditorialGreenBankingDashboard-PKLFy6/App.tsx"),
  "./components/mockups/templates/KintsugiVoyageDepartureCalendar-KxGZgh/App.tsx": () => import("../components/mockups/templates/KintsugiVoyageDepartureCalendar-KxGZgh/App.tsx")
};
